name: captcha-core
version: 0.1.0.0
github: "qwbarch/captcha-haskell"
license: MIT
author: "Edward Yang"
maintainer: "qwbarch@gmail.com"
copyright: "2021 Edward Yang"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/qwbarch/captcha-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl >= 2.2.2 && < 2.3
  - lens >= 4.19.2 && < 5.1
  - wreq >= 0.5.3.3 && < 0.6
  - unliftio >= 0.2.20 && < 0.3
  - text >= 1.2.4.1 && < 1.3
  - bytestring >= 0.10.12.0 && < 0.11
  - data-default-extra >= 0.0.1 && < 0.1
  - cookie >= 0.4.5 && < 0.5
  - aeson >= 1.5.6 && < 1.6
  - o-clock >= 1.2.1 && < 1.3

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wno-name-shadowing
