name: captcha-core
version: 0.1.0.0
github: "qwbarch/captcha-haskell"
license: MIT
author: "Edward Yang"
maintainer: "qwbarch@gmail.com"
copyright: "2021 Edward Yang"
category: Network

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis: A package for integrating a variety of captcha solving services.

description: |
  A package for integrating a variety of captcha solving services.

  Feature list:
  
  * Makes use of the [lens](https://hackage.haskell.org/package/lens) package
  * Mtl-style typeclass, allowing you to use your own monad transformer stack
  * No exceptions are thrown. Errors are shown explicitly through its type signature
  * Minimal test suite provided for each captcha type
  * Captcha services are separated into different packages. Use what you need!

dependencies:
  - base >= 4.7 && < 5
  - mtl >= 2.2.2 && < 2.3
  - lens >= 4.19.2 && < 5.1
  - wreq >= 0.5.3.3 && < 0.6
  - unliftio >= 0.2.20 && < 0.3
  - text >= 1.2.4.1 && < 1.3
  - bytestring >= 0.10.12.0 && < 0.11
  - data-default-extra >= 0.0.1 && < 0.1
  - cookie >= 0.4.5 && < 0.5
  - aeson >= 1.5.6 && < 1.6
  - o-clock >= 1.2.1 && < 1.3
  - string-conversions >= 0.4.0.1 && < 0.5

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wno-name-shadowing
