name: captcha-capmonster
version: 0.1.0.0
github: "qwbarch/captcha-haskell"
license: MIT 
author: "Edward Yang"
maintainer: "qwbarch@gmail.com"
copyright: "2021 Edward Yang"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/qwbarch/captcha-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - captcha-core >= 0.1 && < 0.2
  - http-client >= 0.6.4.1 && < 0.8
  - text >= 1.2.4.1 && < 1.3

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wno-name-shadowing

tests:
  capmonster-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-name-shadowing

    dependencies:
      - captcha-capmonster
